# Generated by Django 5.2.2 on 2026-04-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analyst', 'Analista'), ('user', 'Usuário')], default='user', max_length=16),
        ),
        migrations.CreateModel(
            name='CompanyApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='accounts.company')),
            ],
            options={
                'verbose_name': 'API Key da empresa',
                'verbose_name_plural': 'API Keys das empresas',
            },
        ),
    ]
