# Generated by Django 5.2.2 on 2026-04-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_companyapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('BOLETO', 'Boleto'), ('CARD', 'Cartão de crédito')], default='', max_length=16),
        ),
    ]
