# Generated by Django 5.2.2 on 2026-04-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_preferred_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_complement',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_neighborhood',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_zip_code',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='company',
            name='boleto_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail para boleto'),
        ),
        migrations.AddField(
            model_name='company',
            name='municipal_registration',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='inscrição municipal'),
        ),
        migrations.AddField(
            model_name='company',
            name='nfe_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail para NF-e'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='inscrição estadual'),
        ),
        migrations.AddField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='nome fantasia'),
        ),
    ]
