# Generated by GPT-5.2 on 2026-04-07

from django.db import migrations


def forwards(apps, schema_editor):
    Module = apps.get_model("billing", "Module")
    Plan = apps.get_model("billing", "Plan")
    Subscription = apps.get_model("billing", "Subscription")

    guarantees, _ = Module.objects.get_or_create(
        key="guarantees",
        defaults={
            "name": "Garantias",
            "description": "Módulo de garantias rurais (matrículas, áreas, safras, PDF).",
            "is_active": True,
        },
    )

    Plan.objects.filter(module__isnull=True).update(module=guarantees)
    Subscription.objects.filter(module__isnull=True).update(module=guarantees)

    # Normalizar status legado (do modelo antigo).
    Subscription.objects.filter(status="PAST_DUE").update(status="EXPIRED")


def backwards(apps, schema_editor):
    # Reversão não destrutiva: não removemos dados.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_module_planfeature_remove_plan_max_properties_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

