# Generated by Django 5.2.2 on 2026-04-07 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_seed_module_and_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='billing.module'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.module'),
        ),
    ]
