# Generated by Django 5.2.2 on 2026-04-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CEDULA_RURAL', 'Cédula rural'), ('BARTER', 'Barter'), ('PENHOR', 'Penhor'), ('OUTROS', 'Outros')], max_length=32)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='properties.property')),
            ],
            options={
                'verbose_name': 'Garantia',
                'verbose_name_plural': 'Garantias',
            },
        ),
        migrations.CreateModel(
            name='GuaranteeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_areas', to='properties.area')),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_areas', to='guarantees.guarantee')),
            ],
        ),
        migrations.AddField(
            model_name='guarantee',
            name='areas',
            field=models.ManyToManyField(related_name='guarantees', through='guarantees.GuaranteeArea', to='properties.area'),
        ),
        migrations.AddConstraint(
            model_name='guaranteearea',
            constraint=models.UniqueConstraint(fields=('guarantee', 'area'), name='uniq_guarantee_area'),
        ),
    ]
