# Generated by Django 5.2.2 on 2026-04-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0001_initial'),
        ('properties', '0002_fazenda_area_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='properties.property', verbose_name='fazenda'),
        ),
    ]
