# Generated by Django 5.2.2 on 2026-04-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0003_guarantee_crop_season'),
        ('masterdata', '0001_initial'),
        ('properties', '0004_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='business_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='masterdata.businesspartner', verbose_name='parceiro de negócio'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='cpr',
            field=models.BooleanField(default=False, verbose_name='CPR'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='masterdata.currency', verbose_name='moeda'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='vencimento'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='pledge',
            field=models.BooleanField(default=False, verbose_name='penhor'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='pledge_grade',
            field=models.CharField(choices=[('NONE', 'Não'), ('G1', '1º'), ('G2', '2º'), ('G3', '3º')], default='NONE', max_length=8, verbose_name='grau do penhor'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='principal_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='principal_guarantees', to='properties.area', verbose_name='matrícula principal'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='guarantees', to='masterdata.productionproduct', verbose_name='produtos de produção'),
        ),
    ]
