# Generated by Django 5.2.2 on 2026-04-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_company_address_city_company_address_complement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Parceiro de negócio',
                'verbose_name_plural': 'Parceiros de negócio',
                'constraints': [models.UniqueConstraint(fields=('company', 'cnpj'), name='uniq_partner_company_cnpj')],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='código')),
                ('name', models.CharField(max_length=64, verbose_name='nome')),
                ('symbol', models.CharField(blank=True, default='', max_length=8, verbose_name='símbolo')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_currency_company_code')],
            },
        ),
        migrations.CreateModel(
            name='ProductionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Produto de produção',
                'verbose_name_plural': 'Produtos de produção',
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_prodproduct_company_name')],
            },
        ),
    ]
