# Generated by Django 5.2.2 on 2026-04-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('guarantees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Safra',
                'verbose_name_plural': 'Safras',
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='guarantees.guarantee')),
                ('crop_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='crops.cropseason')),
            ],
            options={
                'verbose_name': 'Empenho',
                'verbose_name_plural': 'Empenhos',
            },
        ),
        migrations.AddConstraint(
            model_name='cropseason',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_cropseason_company_name'),
        ),
    ]
